services:
  atournayre_acceptance_listener:
    class: Atournayre\AcceptanceBundle\Listener\AcceptanceListener
    arguments:
      - '@parameter_bag'
      - '@twig'
    tags:
      - { name: kernel.event_listener, event: kernel.request }
